#! /bin/sh

sxhkd &
/usr/bin/sparky-polkit &
tint2 &
nm-applet &
nitrogen --restore &
(sleep 5s && pnmixer) &
conky --config=/opt/conky/conky-sparky-bspwm.conf &
xfce4-power-manager &
xautolock -time 10 -locker 'i3lock-fancy -g -p' &
xss-lock -- i3lock-fancy -g -p &
thunar --daemon &
xdg-user-dirs-update &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
#bspc config history_aware_focus  true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
